version: "3"
services:
  product-journey:
    command: nuxt
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      API: http://localhost:5000
    volumes:
      - .:/product-journey
