FROM node:current-alpine

WORKDIR /product-journey

COPY package.json /product-journey
COPY yarn.lock /product-journey

EXPOSE $API

ENV HOST 0.0.0.0
ENV API ${API}

RUN yarn install
COPY . /product-journey

ENV NODE_ENV=production

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
